export const mainImage = {
  id: 1,
  url: `${import.meta.env.BASE_URL}images/cover/cover_pic.webp`,
  altText: 'Foto de Capa',
};

export const featuredProducts = [
  {
    id: 1,
    primaryImage: `${import.meta.env.BASE_URL}images/featuredProducts/1a.jpg`,
    secondaryImage: `${import.meta.env.BASE_URL}images/featuredProducts/1b.png`,
    name: 'MOCK NAME 1',
    price: 'R$ 270,00',
    installments: '5x de R$ 56,00',
    altText: 'Produto',
    variants: [
      { color: '#FF0000', size: 34, quantity: 5 },
      { color: '#FF0000', size: 35, quantity: 3 },
      { color: '#FF0000', size: 36, quantity: 0 }, 
      { color: '#000000', size: 34, quantity: 2 },
      { color: '#000000', size: 35, quantity: 4 },
      { color: '#000000', size: 36, quantity: 0 },
    ],
  },
  {
    id: 2,
    primaryImage: `${import.meta.env.BASE_URL}images/featuredProducts/2a.jpg`,
    secondaryImage: `${import.meta.env.BASE_URL}images/featuredProducts/2b.jpg`,
    name: 'MOCK NAME 2',
    price: 'R$ 350,00',
    installments: '5x de R$ 70,00',
    altText: 'Produto',
    variants: [
      { color: '#FF0000', size: 32, quantity: 5 },
      { color: '#FF0000', size: 35, quantity: 3 },
      { color: '#FF0000', size: 36, quantity: 0 }, 
      { color: '#000000', size: 34, quantity: 2 },
      { color: '#000000', size: 35, quantity: 4 },
      { color: '#000000', size: 36, quantity: 1 },
    ],
  },
  {
    id: 3,
    primaryImage: `${import.meta.env.BASE_URL}images/featuredProducts/3a.jpg`,
    secondaryImage: `${import.meta.env.BASE_URL}images/featuredProducts/3b.jpg`,
    name: 'MOCK NAME 3',
    price: 'R$ 740,00',
    installments: '5x de R$ 148,00',
    altText: 'Produto',
    variants: [
      { color: '#FFDB58', size: 34, quantity: 5 },
      { color: '#FFDB58', size: 35, quantity: 3 },
      { color: '#FFDB58', size: 36, quantity: 0 }, 
      { color: '#808080', size: 34, quantity: 2 },
      { color: '#808080', size: 35, quantity: 4 },
      { color: '#808080', size: 36, quantity: 1 },
    ],
  },
];

export const moreProducts = [
  {
    id: 1,
    primaryImage: `${import.meta.env.BASE_URL}images/moreProducts/1a.jpg`,
    secondaryImage: `${import.meta.env.BASE_URL}images/moreProducts/1b.jpg`,
    name: 'MOCK NAME 1',
    price: 'R$ 270,00',
    installments: '5x de R$ 56,00',
    altText: 'Produto',
    variants: [
      { color: '#FF0000', size: 34, quantity: 5 },
      { color: '#FF0000', size: 35, quantity: 3 },
      { color: '#FF0000', size: 36, quantity: 0 }, 
      { color: '#000000', size: 34, quantity: 2 },
      { color: '#000000', size: 35, quantity: 4 },
      { color: '#000000', size: 36, quantity: 1 },
    ],
  },
  {
    id: 2,
    primaryImage: `${import.meta.env.BASE_URL}images/moreProducts/2a.jpg`,
    secondaryImage: `${import.meta.env.BASE_URL}images/moreProducts/2b.jpg`,
    name: 'MOCK NAME 2',
    price: 'R$ 350,00',
    installments: '5x de R$ 70,00',
    altText: 'Produto',
    variants: [
      { color: '#F5F5DC', size: 34, quantity: 5 },
      { color: '#F5F5DC', size: 35, quantity: 3 },
      { color: '#F5F5DC', size: 36, quantity: 0 }, 
      { color: '#000000', size: 34, quantity: 2 },
      { color: '#000000', size: 35, quantity: 4 },
      { color: '#000000', size: 36, quantity: 1 },
    ],
  },
  {
    id: 3,
    primaryImage: `${import.meta.env.BASE_URL}images/moreProducts/3a.jpg`,
    secondaryImage: `${import.meta.env.BASE_URL}images/moreProducts/3b.jpg`,
    name: 'MOCK NAME 3',
    price: 'R$ 740,00',
    installments: '5x de R$ 148,00',
    altText: 'Produto',
    variants: [
      { color: '#FF0000', size: 34, quantity: 5 },
      { color: '#FF0000', size: 35, quantity: 3 },
      { color: '#FF0000', size: 36, quantity: 0 }, 
      { color: '#A9A9A9', size: 34, quantity: 2 },
      { color: '#A9A9A9', size: 35, quantity: 4 },
      { color: '#A9A9A9', size: 36, quantity: 1 },
    ],
  },
  {
    id: 4,
    primaryImage: `${import.meta.env.BASE_URL}images/moreProducts/4a.jpg`,
    secondaryImage: `${import.meta.env.BASE_URL}images/moreProducts/4b.jpg`,
    name: 'MOCK NAME 4',
    price: 'R$ 270,00',
    installments: '5x de R$ 56,00',
    altText: 'Produto',
    variants: [
      { color: '#FFFFFF', size: 34, quantity: 5 },
      { color: '#FFFFFF', size: 35, quantity: 3 },
      { color: '#FFFFFF', size: 36, quantity: 0 }, 
      { color: '#000000', size: 34, quantity: 2 },
      { color: '#000000', size: 35, quantity: 4 },
      { color: '#000000', size: 36, quantity: 1 },
    ],
  },
  {
    id: 5,
    primaryImage: `${import.meta.env.BASE_URL}images/moreProducts/5a.jpg`,
    secondaryImage: `${import.meta.env.BASE_URL}images/moreProducts/5b.jpg`,
    name: 'MOCK NAME 5',
    price: 'R$ 270,00',
    installments: '5x de R$ 56,00',
    altText: 'Produto',
    variants: [
      { color: '#8B4513', size: 34, quantity: 2 },
      { color: '#8B4513', size: 35, quantity: 4 },
      { color: '#8B4513', size: 36, quantity: 1 },
    ],
  },
  {
    id: 6,
    primaryImage: `${import.meta.env.BASE_URL}images/moreProducts/6a.jpg`,
    secondaryImage: `${import.meta.env.BASE_URL}images/moreProducts/6b.jpg`,
    name: 'MOCK NAME 6',
    price: 'R$ 320,00',
    installments: '5x de R$ 64,00',
    altText: 'Produto',
    variants: [
      { color: '#FFD700', size: 34, quantity: 8 },
      { color: '#FFD700', size: 35, quantity: 6 },
      { color: '#FFD700', size: 36, quantity: 3 },
      { color: '#000000', size: 34, quantity: 4 },
      { color: '#000000', size: 35, quantity: 2 },
      { color: '#000000', size: 36, quantity: 0 }, 
    ],
  },
  {
    id: 7,
    primaryImage: `${import.meta.env.BASE_URL}images/moreProducts/7a.jpg`,
    secondaryImage: `${import.meta.env.BASE_URL}images/moreProducts/7b.jpg`,
    name: 'MOCK NAME 7',
    price: 'R$ 190,00',
    installments: '3x de R$ 63,33',
    altText: 'Produto',
    variants: [
      { color: '#87CEEB', size: 34, quantity: 10 },
      { color: '#87CEEB', size: 35, quantity: 5 },
      { color: '#87CEEB', size: 36, quantity: 2 },
      { color: '#808080', size: 34, quantity: 6 },
      { color: '#808080', size: 35, quantity: 4 },
      { color: '#808080', size: 36, quantity: 1 },
    ],
  },
  {
    id: 8,
    primaryImage: `${import.meta.env.BASE_URL}images/moreProducts/8a.jpg`,
    secondaryImage: `${import.meta.env.BASE_URL}images/moreProducts/8b.jpg`,
    name: 'MOCK NAME 8',
    price: 'R$ 450,00',
    installments: '5x de R$ 90,00',
    altText: 'Produto',
    variants: [
      { color: '#FF4500', size: 34, quantity: 2 },
      { color: '#FF4500', size: 35, quantity: 0 }, 
      { color: '#FF4500', size: 36, quantity: 5 },
      { color: '#2E8B57', size: 34, quantity: 3 },
      { color: '#2E8B57', size: 35, quantity: 7 },
      { color: '#2E8B57', size: 36, quantity: 4 },
    ],
  },
  {
    id: 9,
    primaryImage: `${import.meta.env.BASE_URL}images/moreProducts/9a.jpg`,
    secondaryImage: `${import.meta.env.BASE_URL}images/moreProducts/9b.jpg`,
    name: 'MOCK NAME 9',
    price: 'R$ 290,00',
    installments: '4x de R$ 72,50',
    altText: 'Produto',
    variants: [
      { color: '#FF1493', size: 34, quantity: 5 },
      { color: '#FF1493', size: 35, quantity: 2 },
      { color: '#FF1493', size: 36, quantity: 0 }, 
      { color: '#4B0082', size: 34, quantity: 3 },
      { color: '#4B0082', size: 35, quantity: 4 },
      { color: '#4B0082', size: 36, quantity: 6 },
    ],
  },
  {
    id: 10,
    primaryImage: `${import.meta.env.BASE_URL}images/moreProducts/10a.jpg`,
    secondaryImage: `${import.meta.env.BASE_URL}images/moreProducts/10b.jpg`,
    name: 'MOCK NAME 10',
    price: 'R$ 530,00',
    installments: '6x de R$ 88,33',
    altText: 'Produto',
    variants: [
      { color: '#8A2BE2', size: 34, quantity: 4 },
      { color: '#8A2BE2', size: 35, quantity: 6 },
      { color: '#8A2BE2', size: 36, quantity: 3 },
      { color: '#5F9EA0', size: 34, quantity: 7 },
      { color: '#5F9EA0', size: 35, quantity: 5 },
      { color: '#5F9EA0', size: 36, quantity: 2 },
    ],
  },
  {
    id: 11,
    primaryImage: `${import.meta.env.BASE_URL}images/moreProducts/11a.jpg`,
    secondaryImage: `${import.meta.env.BASE_URL}images/moreProducts/11b.jpg`,
    name: 'MOCK NAME 11',
    price: 'R$ 410,00',
    installments: '5x de R$ 82,00',
    altText: 'Produto',
    variants: [
      { color: '#DC143C', size: 34, quantity: 5 },
      { color: '#DC143C', size: 35, quantity: 3 },
      { color: '#DC143C', size: 36, quantity: 2 },
      { color: '#FFDAB9', size: 34, quantity: 6 },
      { color: '#FFDAB9', size: 35, quantity: 4 },
      { color: '#FFDAB9', size: 36, quantity: 1 },
    ],
  },
  {
    id: 12,
    primaryImage: `${import.meta.env.BASE_URL}images/moreProducts/12a.jpg`,
    secondaryImage: `${import.meta.env.BASE_URL}images/moreProducts/12b.jpg`,
    name: 'MOCK NAME 12',
    price: 'R$ 360,00',
    installments: '4x de R$ 90,00',
    altText: 'Produto',
    variants: [
      { color: '#800080', size: 34, quantity: 8 },
      { color: '#800080', size: 35, quantity: 5 },
      { color: '#800080', size: 36, quantity: 3 },
      { color: '#4682B4', size: 34, quantity: 7 },
      { color: '#4682B4', size: 35, quantity: 2 },
      { color: '#4682B4', size: 36, quantity: 0 },
    ],
  },
];